---
name: Matthew J Grainger
position: "Researcher"
address: "Norwegian Institute for Nature Research"
phone: 
www: uncertainecologist.netlify.com
email: "Matthew.Grainger@nina.no"
twitter: Ed_pheasant
github: DrMattG
aboutme: Wildlife, Uncertainty, Evidence synthesis, Decision models
linkedin: www.linkedin.com/in/matthew-grainger-49880a36
date: "`r format(Sys.time(), '%B %Y')`"
output:
  vitae::awesomecv:
    keep_tex: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(tidyverse)
library(RefManageR)
library(vitae)
library(scholar)
source("C:/Users/matthew.grainger/Documents/Employment_Docs/Markdown_CV/Robjhyndman_Baretable.R")
```


# Education and qualifications

```{r degrees, results='asis'}
tribble(

  ~ degree, ~ uni, ~ loc, ~ dates,

  "BSc (Hons) in Zoology", "Newcastle University", "Newcastle upon Tyne, UK", "1994 - 1997",

  "MSc in Conservation & planning", "University of Pretoria", "Gauteng, South Africa", "2004 - 2005", 

  "PhD Zoology", "University of Pretoria", "Gauteng, South Africa", "2008 - 2012" 
) %>% 

  detailed_entries(degree, dates, uni, loc)

```

# Employment history


```{r employment, results='asis'}

tribble(

  ~Start, ~End, ~Position,

  2005, 2006, "\\textbf{Research Co-ordinator}, Frontier Tanzania, Terrestrial projects, Tanzania",

  2011, 2012, "\\textbf{Conservation Research and Support Officer}, The World Pheasant Association, Close House, Wylam, Newcastle, UK",

  2013, 2014, "\\textbf{Postdoctoral Research Associate}, Research Impact (Faculty of Science, Agriculture and Engineering), Newcastle University, Newcastle, UK",

  2014, 2019, "\\textbf{Postdoctoral Research Associate}, Modelling Evidence and Policy Group, Newcastle University, Newcastle, UK",

  2019, 2021, "\\textbf{Postdoctoral Fellow},Terrestrial biodiversity, Norwegian Institute for Nature Research, Trondheim, Norway",
  2021, NA , "\\textbf{Researcher},Terrestrial biodiversity, Norwegian Institute for Nature Research, Trondheim, Norway"

) %>%

  arrange(-Start) %>%

  #filter(Start > 2000) %>%

  mutate(End = replace_na(End, "")) %>%

  mutate(Years = paste(Start, "--", End, sep = "")) %>%

  select(Years, Position) %>%

  baretable()

```


# Publications

```{r}
scholar::get_publications("aZ4E5I4AAAAJ&hl") %>%

  arrange(desc(year)) %>%

  detailed_entries(

    what = title,

    when = year,

    with = author,

    where = journal

  )
```
